name: Build Kivy/Python Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # الخطوة 1: جلب كود المشروع
      - name: Checkout repository
        uses: actions/checkout@v4

      # الخطوة 2: إعداد التخزين المؤقت (Caching) لتسريع عمليات البناء
      - name: Cache Buildozer and Pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.local/share/pip
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: ${{ runner.os }}-buildozer-

      # الخطوة 3: تثبيت Java Development Kit (JDK) 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # الخطوة 4: تثبيت Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ========================================================================
      # **الجزء الحاسم لحل جميع مشاكل SDK وأدوات البناء**
      # ========================================================================

      # الخطوة 5: تثبيت Android SDK لتوفير أداة sdkmanager
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # الخطوة 6: قبول التراخيص وتثبيت أدوات البناء اللازمة
      - name: Accept Licenses and Install Build-Tools
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager "build-tools;34.0.0" "platforms;android-34"

      # الخطوة 6.1: إضافة build-tools و platform-tools للمسار
      - name: Add Android SDK tools to PATH
        run: |
          echo "${ANDROID_SDK_ROOT}/build-tools/34.0.0" >> $GITHUB_PATH
          echo "${ANDROID_SDK_ROOT}/platform-tools" >> $GITHUB_PATH

      # (اختياري) طباعة محتوى build-tools للتأكد من وجود الملفات
      - name: List build-tools directory
        run: ls -l ${ANDROID_SDK_ROOT}/build-tools/34.0.0

      # الخطوة 7: تثبيت متطلبات Buildozer ومكتبات النظام
      - name: Install Buildozer and system dependencies
        run: |
          sudo apt-get update
          # حزم عامة للبرمجة والمكتبات
          sudo apt-get install -y --no-install-recommends \
            git zip unzip autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          # حزم Pango, Cairo, GLib، وتبعياتها لعرض الخطوط والرسومات
          sudo apt-get install -y --no-install-recommends \
            libglib2.0-dev libpango1.0-dev libcairo2-dev libfreetype6-dev libfontconfig1-dev
          # لبعض مكونات Kivy الأخرى التي قد تتطلبها (مثل SDL2)
          sudo apt-get install -y --no-install-recommends \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libxml2-dev libxslt1-dev libjpeg-dev libpng-dev
          
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.36
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # الخطوة 8: بناء التطبيق باستخدام Buildozer
      - name: Build with Buildozer
        run: buildozer -v android debug

      # الخطوة 9: رفع ملف APK كمنتج نهائي
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-calculator-apk
          path: bin/*.apk
          if-no-files-found: error
          retention-days: 7
